### PR TITLE
make Tabula work under a relative path

### LINKED ISSUE #110: Make URLs relative so Tabula works if not running on the root path
I'm playing with deploying tabula to a servlet container (tomcat). Most URLs in Tabula (references to CSS and JS scripts, redirects, images, etc) are absolute to the root path, so it doesn't works when the app is running under a different context.

It would also break if Tabula is running under a reverse proxy, that serves the app on a non-root path.

If running as a servlet (ie. `$servlet_context` is defined), get the root URI with `$servlet_context.getContextPath`

If running standalone, I guess we should allow to configure it from a environment variable or something.

### PR DESCRIPTION
**Pull request by jeremybmerrill**
@jazzido and @theta682: Check out this branch and see if it works for you, in the situation you envision for running Tabula under a subpath.

`ROOT_URI=tabula bundle exec rackup` should serve a working version of Tabula under `localhost:9292/tabula/`.

I wasn't able to figure out how to set a context path, because my familiarity with Jetty, Tomcat, etc. is basically nothing. So that may not work, but it should be an easy fix at the top of config.ru

will close #110 and #547

### CODE REVIEW

**Comment by jeremybmerrill** [comment]
@mtigas @jazzido can one of you guys take a look at this and make sure nothing is obviously broken?

**Comment by jazzido** [comment]
LGTM

**Comment by jeremybmerrill** [comment]
tyvm

**Comment by jimzucker** [comment]
@jeremybmerrill I have been trying to make ROOT_URI, I set an env variable and passed -D ROOT_URI=xx to my docker container but not luck, can you give me a hint do we have modify a file?

**Comment by jeremybmerrill** [comment]
@jimzucker Can you say more about what goes wrong?

**Comment by jimzucker** [comment]
@jeremybmerrill we are trying to run this container with a different root like /pdf instead of / but we have not found how to set the root in the currently available docker container on docker hub.  This is so we can make the container part of a larger website and proxy a route. as we use / for other things we need to add a different root.

**Comment by jeremybmerrill** [comment]
Right, so, what happens when you try? Does Tabula not respond at all under the chosen root? Or does it respond, but not work properly once you're interacting with Tabula?

**Comment by jeremybmerrill** [comment]
FYI, this may've been a typo in your above bug, but the right way to set an env var in Docker is like this `docker run -e ROOT_URI=tabula -p 9292:9292 tabula` (with `-e` not `-D`)

**Comment by learningNLP** [comment]
I tried to add this env ROOT_URI=tabula at run time . It get started but while file upload it fails .

**Comment by AbhishekTrivedi2017** [comment]
FYI , I tried with docker run -e ROOT_URI=tabula -p 9292:9292 tabula . It get started on desired url but fails while uploading pdf .

**Comment by jeremybmerrill** [comment]
@AbhishekTrivedi2017 can you try it again? I think I fixed that with 87cbba4, which I pushed just now.

**Comment by AbhishekTrivedi2017** [comment]
Thanks . It is working fine as expected @jeremybmerrill .....

**Comment by jeremybmerrill** [comment]
@AbhishekTrivedi2017 Great, thanks for verifying.

**Comment by PrajjvalGupta** [comment]
@jeremybmerrill I am not able to build docker image locally for this fix . Here is the screen shot for this
image (3)

**Comment by PrajjvalGupta** [comment]
@jeremybmerrill  
image (3)
While creating the docker image locally, i am getting the following error:

**Pull request merged**
