### PR TITLE
Change default port from 8080 to 35444 (see #322)

### PR DESCRIPTION
**Pull request by jazzido**
Hey @jeremybmerrill, can you review when you get the chance? It's a simple change, but want to make sure :)

Thanks!

### CODE REVIEW

**Comment by jeremybmerrill** [comment]
I haven't run this yet, but where does this set the jetty.port? (it looks like it reads it to send the browser there, but don't we have to tell jetty to run there?)

**Comment by jazzido** [comment]
`35444` is the [default](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#getInteger%28java.lang.String,%20int%29) in the the `java.lang.Integer.getInteger('jetty.port', 35444)`.

The user can choose to override `jetty.port` by passing a JVM preference, as described in our docs.

**Comment by jeremybmerrill** [comment]
Got it. So how does that get sent to Jetty? I only see the command to tell the browser to open on that port -- not anything telling Jetty to listen on that port.

**Comment by jazzido** [comment]
that's taken care of by warbler, rackup, or any of the hundreds of middlewares we use :)

**Comment by jeremybmerrill** [comment]
Okay, I tried this out (running the jar) and it doesn't work for me. The server still starts on 8080. (The browser correctly goes to 35444, but there's of course nothing listening there.)

**Comment by jazzido** [comment]
You're right. I was too optimistic, changing the default port with Warbler it's a bit more involved. Let's put it on hold for now.

**Comment by jeremybmerrill** [comment]
Bummer! I think this is a good idea in any case.

**Comment by jeremybmerrill** [comment]
Although! Can we figure out a port that spells out Tabula or something? `748?14`?

**Comment by jazzido** [comment]
Port numbers need to be < 64k :(

**Comment by jeremybmerrill** [comment]
Oh that's true, damnit

**Pull request merged**
