### PR TITLE
working deb package, all deps solved

### PR DESCRIPTION
**Pull request by pachamaltese**
@jazzido 

capitán

estoy usando mucho tabula en la oficina hasta hice un auto instalador para Windows y todo

acá va un script que crear un deb que funciona en Debian y Ubuntu y lo que hace es:
1. hacer el build con jruby
2. armar un deb
3. crear los iconos, accesos directos y un link en /bin que llama a tabula desde /opt y te abre el browser automáticamente

como no veo un deb en tabula.technology quizá esto les sirve
a diferencia de un experimento anterior, este build no usa herramientas que no sean el package builder de Debian y usa el fuente de tabula directamente

saludos !!

### CODE REVIEW

**Comment by jazzido** [comment]
Thanks @pachamaltese ! (And sorry for the delay in getting back)

I'm not familiar with the process for proposing new packages to Debian, but I think it's more appropiate to start that process rather than including packaging code in the Tabula code base. In any case, we'd be happy to create a new repository in the `tabulapdf` organization to hold these scripts.

Is that something that you'd be interested in doing?

Thanks!

**Comment by pachamaltese** [comment]
@jazzido sure! let's do that

**Comment by pachamaltese** [comment]
@jazzido Hi. I moved everything to https://github.com/pachamaltese/tabula-deb and to keep it DRY the source (i.e the jar) is considered in .gitignore
Here's a working DEB that probably you'd like to add to tabula.technology https://github.com/pachamaltese/tabula-deb/releases
To install it just run `sudo gdebi tabula.deb`

**Comment by pachamaltese** [comment]
hi @jazzido, any news about the deb? did you like it?

**Comment by jeremybmerrill** [comment]
@pachamaltese Sorry for the delay. I love it! I don't know much about Debian packaging, but the package worked great for me.

My only nit-pick is that it echoes `dpkg-deb: building package 'tabula' in 'deb-package.deb'.`. That is not a big problem though.

I like how you made the icon open Tabula in a terminal. That makes sense because we don't have an in-browser way to quit the Tabula process (though I've tried...).

What do you think the best way would be to make this official? We could host the Deb on tabula.technology... we could put it in the official Ubuntu software repos, though I don't have any idea how to make that happen.

**Comment by pachamaltese** [comment]
Hi @jeremybmerrill 
Thanks ! The only hard part is the latter, building a PPA (the step before submitting to Ubuntu development repo) requires some automated scripts to build from source on a kind of virtual machine.
Here's a list of TODOs based on your feedback:
- [ ] build package straight to `tabula-X.X.XXX.deb`
- [ ] prepare DEB for website
- [ ] create PPA?

**Comment by jeremybmerrill** [comment]
That sounds right to me. It looks like creating this to work with a PPA may be more complicated than I expected; maybe just putting the DEB on the website is a good goal for now.

**Pull request closed without merging**
