### PR TITLE
upgrading to tabula-java-1.0.0

### PR DESCRIPTION
**Pull request by jazzido**
Hey @jeremybmerrill and @mtigas 

I released tabula-java 1.0.0 to Maven earlier today, so I think it's time to upgrade Tabula. This PR also gets rid of JPedal, using PDFBox directly for rendering page thumbnails.

Can you help me test it?

### CODE REVIEW

**Comment by jazzido** [comment]
@jeremybmerrill can you take a look at this one while you're at it? :)

**Comment by jeremybmerrill** [comment]
@jazzido I'm getting empty responses on a PDF that *should* work (and do work off of `master`) from this. 

For several different selections that work on master, I get this response for each, regardless of the extraction method I choose: `[{"extraction_method":"","top":0.0,"left":0.0,"width":0.0,"height":0.0,"data":[[{"top":0.0,"left":0.0,"width":0.0,"height":0.0,"text":""}]], "spec_index": 0}]`. The params to the request _look_ right (and do work right, as I said, on master).

Does any of that ring a bell as to what could be happening? (It's *possible*, I guess, that my local environment is screwed up...?)

**Comment by jazzido** [comment]
The only change besides using PDFBox for rendering, was upgrading `tabula-java` to 1.0.0.

That means that your extraction should also fail in 1.0.0. Can you try reproducing that with 0.9.2 and 1.0.0?

Thanks?

**Comment by jeremybmerrill** [comment]
Interesting, looks like it: `java -jar lib/jars/tabula-1.0.0-jar-with-dependencies.jar -a 193.163,34.425,333.158,365.67 ~/Downloads/cs-en-us-pbms.pdf` does also return an empty string.

**Comment by jazzido** [comment]
Then it's a bug. Can you send me that PDF?

**Comment by jeremybmerrill** [comment]
http://www1.nyc.gov/assets/nypd/downloads/pdf/crime_statistics/cs-en-us-pbms.pdf

**Comment by jazzido** [comment]
Thanks. Just added tabulapdf/tabula-java#171

**Comment by jazzido** [comment]
Tested locally with tabulapdf/tabula-java#173, seems to work fine. Will update this branch with the new version of tabula-java as soon as I cut a release to Maven.

**Comment by jazzido** [comment]
@jeremybmerrill @mtigas I went ahead and closed #418 on this PR. Besides removing the ugly fat jar from the repo, it'll force us to depend only on released versions of `tabula-java`.

There's an additional build step, I updated the `README` accordingly.

Let me know what you think.

**Comment by jeremybmerrill** [comment]
Oh cool!

**Comment by jazzido** [comment]
Can't get Travis to build. Works on my machine, but can't figure it out. Any idea?

**Comment by jeremybmerrill** [comment]
I was testing the new tabula-java-1.0.0 version for #710. I got the following, which I think would be an easy fix in tabula-java, right? (Or maybe in JBundler?)
`SEVERE: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed`

fix is probably something like: 

````
            <dependency>
                <groupId>com.github.jai-imageio</groupId>
                <artifactId>jai-imageio-core</artifactId>
                <version>1.3.1</version>
            </dependency>    
            <dependency>
                <groupId>com.github.jai-imageio</groupId>
                <artifactId>jai-imageio-jpeg2000</artifactId>
                <version>1.3.0</version>
            </dependency>
````

**Comment by jazzido** [comment]
Yes, I added that in [173575835fc9ce28f4589b09761771b676a051c2](https://github.com/tabulapdf/tabula-java/commit/173575835fc9ce28f4589b09761771b676a051c2). 

If you want to test that locally:

  - build tabula-java: `mvn clean package -DskipTests=true`
  - install it to your local Maven repo: `mvn install:install-file -Dfile=target/tabula-1.0.1-SNAPSHOT.jar -DgroupId=technology.tabula -DartifactId=tabula -Dversion=1.0.1-SNAPSHOT -Dpackaging=jar -DpomFile=pom.xml`
  - Update `tabula-java` version in the `Jarfile`: `jar 'technology.tabula:tabula', '1.0.1-SNAPSHOT'`
  - Update the JBundle: `bundle exec jbundle update`
  - Run tabula from source: `jruby -G -r jbundler -S rackup`

**Comment by jazzido** [comment]
Hey @jeremybmerrill ,

Per [this comment](https://github.com/tabulapdf/tabula/pull/705#issuecomment-316109313) on your _templates_ branch, I went ahead and refactored the mess that was handling the JSON files directly. There is now a `Tabula::Workspace` singleton that should be used for all the operations that change Tabula's "database".

**Comment by jazzido** [comment]
For some reason, I had to make this change in the JS file: https://github.com/tabulapdf/tabula/commit/d8b78842354af654bc733f557d778cfa5c961b69#diff-fff9bb0a50951159728ad6c9b7967b07R38

(I kinda lost track of what's going on in the frontend)

**Comment by jazzido** [comment]
I think it's looking pretty good for merging to `master`. Any outstanding issues?

BTW, I vote for bumping up to `1.2.0`.

**Comment by jeremybmerrill** [comment]
Yes, a beta first?. 

Let me get a fix for the button feedback thing. Will be done by EOD.

And I'll aim to fix the anchors on the page thumbnails before we release 1.2.0 for real.

**Comment by jazzido** [comment]
> Yes, a beta first?.

Sounds good.

> Let me get a fix for the button feedback thing. Will be done by EOD.

👍🏼

> And I'll aim to fix the anchors on the page thumbnails before we release 1.2.0 for real.

Wouldn't a simple `e.eventPropagation()` fix that?

**Comment by jeremybmerrill** [comment]
> > And I'll aim to fix the anchors on the page thumbnails before we release 1.2.0 for real.
> Wouldn't a simple e.eventPropagation() fix that?

How so? I think the problem is that there's no JavaScript involved in that navigation, it's just the browser's built-in behavior for anchors. But with the new-ish `<base>` tag, `href="#"` is interpreted as navigating to the "base" URL.

**Comment by jazzido** [comment]
Oh, gotcha. It's been a while since I touched the frontend code :)

**Comment by jeremybmerrill** [comment]
Okay, I added the feedback.

**Comment by jazzido** [comment]
Now I'm being annoying :) Is there a way to make the template buttons wrap nicely?

image

**Comment by jeremybmerrill** [comment]
Man you must have a tiny screen. But yeah, I should figure out how to do that.

Got any layout ideas? I was thinking about making the autodetected tables show up as if they were a template (because they, kind of, are).

Maybe I'll right-align the Preview & Export Extract Data button, since it's the main button you'd use. Hmm...

**Comment by jazzido** [comment]
> Got any layout ideas?

File name on the first line, buttons below?

**Comment by jazzido** [comment]
Should I go ahead and merge to `master`?

**Comment by jeremybmerrill** [comment]
@jazzido if you're cool with releasing a beta with these two bugs, sure. (the buttons wrapping funny on smaller screens; the thumbnail clicking being broken)

**Comment by jazzido** [comment]
OK, I'm going to go ahead and merge to `master`. Thanks for fixing #712 !

**Pull request merged**
