### PR TITLE
Add option to disable the latest version check (from Github) and the …

### PR DESCRIPTION
**Pull request by rossigee**
…stats notification callback (to 'jeremybmerrill.com') (refs #924).

### CODE REVIEW

**Comment by jazzido** [comment]
Thanks a lot @rossigee!

The PR looks good. Would you be able to add a short note in [this section](https://github.com/tabulapdf/tabula#why-tabula) of the `README` file describing the properties that toggle notifications?

**Comment by rossigee** [comment]
Added some notes about the new options.

**Comment by jazzido** [comment]
Thanks a lot @rossigee — Merging.

**Comment by rossigee** [comment]
When can we expect a new release that includes this patch?

The latest release is now over a year old, and is missing ~585 useful commits to master...

https://github.com/tabulapdf/tabula/releases

**Pull request merged**
