### PR TITLE
Repeat to Specified Pages

### PR DESCRIPTION
**Pull request by rosenjcb**
There have been recent requests [here](https://github.com/tabulapdf/tabula-java/issues/250) and [here](https://github.com/tabulapdf/tabula/issues/909) for the ability to repeat a given selection to a certain page number. Coincidentally, I have implemented that same feature in my own fork with some extended functionality. 

This feature allows the user to specify a range or ranges of pages to repeat a given selection to (e.g. 2-12, 14-16, 20-30). An alert box will appear, let the user enter their range(s), use regex to check if the range is valid, and then repeat the given selection if it is. 

This is pretty much my first pull request, so I am still learning the etiquette and proper procedure. If there is anything wrong with my feature or if there needs to be anything added to it (e.g. prevent overlapping selections) before it can be accepted, please let me know.

### CODE REVIEW

**Comment by jazzido** [comment]
Hi @rosenjcb,

Thanks for submitting this PR. This is something that we wanted to add, so I'll be happy to work with you in potentially merging this into Tabula. Couple notes:

  - I noticed that you based your work on a _fork_ of Tabula. Can you resubmit a PR based on the current `master` branch?
  - When you do, please make sure that your editor does not reformat the code. It is way easier to review the changes that way.

I'll go ahead and close this PR. Feel free to resubmit when you have the chance.

Thanks again!

**Comment by rosenjcb** [comment]
@jazzido So essentially I made a fork of my boss' fork. I then made a new branch and reverted those changes to what I thought was the most recent commit on the branch on the original tabula project. It is possible my boss didn't upstream the changes to his repo. 

How would you recommend I upstream the most recent changes to my fork? I cannot make a fork of the original project since I already made a fork of my boss' fork. 

I will take care of the whitespace issues as well.

**Comment by jazzido** [comment]
Never tried this, but you might be able to a remote that points to `https://github.com/tabulapdf/tabula.git` (`tabula` official repo) and branch off that repo's `master`. Make your changes there, push to a branch in _your_ fork and then submit a PR to our repo.

**Comment by jazzido** [comment]
BTW, instead of using regex to parse the page range specification, you might want to take a look at `Utils.parsePagesOption` in `tabula-java`.

https://github.com/tabulapdf/tabula-java/blob/1e9a6129f61ba7031f49fe06276a0cc69ff135ac/src/main/java/technology/tabula/Utils.java#L160-L188

**Pull request closed without merging**
