### PR TITLE
ArchLinux package informations

### PR DESCRIPTION
**Pull request by nim65s**
A package is available at https://aur.archlinux.org/packages/tabula/

And about "Spreading the word about Tabula", create easy to use Linux packages may sound as a good start :)

### CODE REVIEW

**Comment by jazzido** [comment]
Thanks a lot @nim65s!

Did you build from `master` or `stable/1.0.x`?

**Comment by nim65s** [comment]
For now, this package is bound to a stable version (ie. it downloads https://github.com/tabulapdf/$pkgname/releases/download/v$pkgver/$pkgname-jar-$pkgver.zip) 
We can also create a "tabula-git" package which clones the `master` branch.

**Comment by jazzido** [comment]
Thanks, I  just saw the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tabula).

In that case, can you apply your change to the `stable/1.0.x` branch and resubmit the pull request? I'll merge to our `stable/1.0.x` branch.

Thanks!

**Comment by nim65s** [comment]
Done :)

**Comment by nim65s** [comment]
Merged in #403

**Pull request closed without merging**
