### PR TITLE
Implmement new table detector

### PR DESCRIPTION
**Pull request by jazzido**
Hey @jeremybmerrill, @mtigas,

I've just integrated @mcharters's contribution to Tabula-UI. Can you review and help me test it?

Thanks!

### CODE REVIEW

**Comment by jeremybmerrill** [comment]
What should I be looking for?

**Comment by jazzido** [comment]
- Obvious mistakes in the code (it's a 3-line change)
  - table detection: throw some PDFs at it and check how the autodetection feature performs.

**Comment by jazzido** [comment]
Yo @jeremybmerrill, did you have the chance to check this?

**Comment by jeremybmerrill** [comment]
nope, not yet! not sure when I"ll get a chance, but I put it on my calendar
for Sunday

On Wed, Feb 17, 2016 at 12:52 PM, Manuel Aristarán <notifications@github.com

**Comment by jazzido** [comment]
Cool. The patch is exactly 3 lines long, but I'd like that someone else throws a few tables at this thing.

**Comment by jeremybmerrill** [comment]
looks good to me!

(I just ran some tables through, didn't seem to run itno issues)

**Comment by jeremybmerrill** [comment]
and, I should say, autodetect worked in the cases that I tried

**Pull request merged**
